### ISSUE TITLE
Why is there some oracle/java stuff redirection in the extension?

### ISSUE THREAD

**Issue by rbrito** [rNeomy/last.fm-scrobbler#1]
In file https://github.com/rNeomy/last.fm-scrobbler/blob/master/youtube/data/inject.js, I see some   manipulation of the location of the URL that the user might visit that is beyond the scope of this extension.

Can you explain why this is there?

**Comment by rNeomy** [comment]
Thanks for the report. The script is left off from another project! Fortunately it has no effect at all. Actually it is not even being called. I'll remove it by the next release

https://github.com/rNeomy/last.fm-scrobbler/blob/master/youtube/manifest.json#L22-L41
