### ISSUE TITLE
manually entered details don't validate

### ISSUE THREAD

**Issue by bitoolean** [rNeomy/last.fm-scrobbler#15]
I had checked the "check manually entered details with last.fm before scrobbling". Now when listening to https://youtu.be/jRhGjPoNqBY , I got an error message bar saying the track was skipped and I "clicked to edit" to fix the title, but the message just reappears after a few seconds that the track was not found and was skipped from scrobbling.

The track details were correctly identified though as UFO and I edited the title to remove the parentheses, to "I'm A Loser" exactly as on last.fm.

I'm using the latest Firefox, and the NoScript addon, but disabling it on the tab didn't fix this.

**Comment by rNeomy** [comment]
Thanks for the report. It is now fixed by https://github.com/rNeomy/last.fm-scrobbler/issues/27
