### ISSUE TITLE
Playlists with track numbers are parsed incorrectly

### ISSUE THREAD

**Issue by nighto** [rNeomy/last.fm-scrobbler#22]
Consider this example: https://www.youtube.com/watch?v=O9Dcs9U7rXM

```
00:00 01. Bad Company - Riptide
06:40 02. Jorge Ben & Toquinho - Carolina Carol Bela (DJ Marky & XRS Remix)
11:03 03. Shy FX - Shake It
15:04 04. Un-Cut - Midnight
19:55 05. Shimon - Hush Hush
24:06 06. Stakka & Skynet & DJ Friction - Altitude
28:23 07. Future Cut - Dainjah
33:31 08. Hatiras vs. J Majik - Spaced Invader
39:00 09. Ed Rush & Optical - Kerb Crawler
44:29 10. High Contrast - Make It Tonight
50:09 11. Q Project - Trouble
54:21 12. Digital - Gateman
59:37 13. Bad Company - Miami Flashback
```

We could try to ignore the initial `/%d%d?\./` part.

**Comment by nighto** [comment]
Tried patching `clearString` function by adding on line 40 another replace:

```
.replace(/^\s?\d+\s*[.-]\s?/, '');
```

but that ended up creating duplicated scrobbles, one correct and one incorrect, not sure why:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/397851/104748114-a066ef00-5751-11eb-8469-12a49565ba45.png">

**Comment by rNeomy** [comment]
Try https://github.com/rNeomy/last.fm-scrobbler/commit/f576f79db6ff1d57af11758770843067adc86be2 and let me know if it is fixed or not

**Comment by nighto** [comment]
Hi @rNeomy, it does not. It's still duplicated:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/397851/105215558-5151fd00-5b49-11eb-8e02-8fc4e4a0a5fe.png">
