### ISSUE TITLE
[feature request] Enable support for YouTube Music

### ISSUE THREAD

**Issue by CBiederman** [rNeomy/last.fm-scrobbler#23]
Is it possible to update this plug-in to also work on music.youtube.com? It works perfectly on youtube.com, but I find that the interface on music.youtube.com is much better polished (and tailored specifically for an audio listening experience) -- would be great if this plug-in would be able to scrobble from YouTube Music.

**Comment by rNeomy** [comment]
Hopefully by the next release!
