### ISSUE TITLE
[Security Flaw] Your Last.FM token keys are exposed to the public

### ISSUE THREAD

**Issue by mixcoac** [rNeomy/last.fm-scrobbler#24]
Hey, I've been checking through your repo due to the extension not working on my device and stumbled upon that your `lastfm.js` file has a variable called "lastfm" with what seems to be the public and secret tokens that give you access to the LastFM API.

From what I know, its not a big deal but as the saying goes, "its better to be safe than sorry".

---

My suggestion to fix this is making 1 (or 2) files with the keys and inputing the files into the `.gitignore` file.

You can just make an import with the keys (if i'm not wrong) and use them that way.

(re-gen your token too lol)

**Comment by rNeomy** [comment]
I wish there was a way to hide keys. Even if I hide them in the GitHub repo, the source code of extensions is accessible online.
