### ISSUE TITLE
Feature-Request: Enhance title cleaning

### ISSUE THREAD

**Issue by Gargamelism** [rNeomy/last.fm-scrobbler#8]
Anything in brackets is usually not relevant, and resulting strings should be trimmed

**Comment by rNeomy** [comment]
We have it optionally which is enabled by default. We can also extend the cleaning capability; https://github.com/rNeomy/last.fm-scrobbler/blob/master/youtube/data/scrobbler/protected.js#L239

**Comment by Gargamelism** [comment]
Cool, can we add round brackets as well?
